{% set version = "1.2.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-solrium
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/solrium_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/solrium/solrium_{{ version }}.tar.gz
  sha256: 7ec64199497cc69f542fded955b709fc548cf8e2734c9db0f4a99a0ea67ca49b

build:
  number: 3
  script: R CMD INSTALL --build .
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-r6
    - r-crul >=0.4.0
    - r-dplyr >=0.5.0
    - r-jsonlite >=1.0
    - r-plyr >=1.8.4
    - r-tibble >=1.4.2
    - r-xml2 >=1.0.0
  run:
    - r-base
    - r-r6
    - r-crul >=0.4.0
    - r-dplyr >=0.5.0
    - r-jsonlite >=1.0
    - r-plyr >=1.8.4
    - r-tibble >=1.4.2
    - r-xml2 >=1.0.0

test:
  commands:
    - $R -e "library('solrium')"           # [not win]
    - "\"%R%\" -e \"library('solrium')\""  # [win]

about:
  home: https://github.com/ropensci/solrium (devel), https://docs.ropensci.org/solrium/ (user manual)
  license: MIT
  summary: Provides a set of functions for querying and parsing data from 'Solr' (<https://lucene.apache.org/solr>) 'endpoints' (local and remote), including search, 'faceting', 'highlighting', 'stats', and 'more like this'. In addition, some functionality is included for creating, deleting, and updating documents in a 'Solr'
    'database'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: solrium
# Title: General Purpose R Interface to 'Solr'
# Description: Provides a set of functions for querying and parsing data from 'Solr' (<https://lucene.apache.org/solr>) 'endpoints' (local and remote), including search, 'faceting', 'highlighting', 'stats', and 'more like this'. In addition, some functionality is included for creating, deleting, and updating documents in a 'Solr' 'database'.
# Version: 1.1.0
# Authors@R: c( person("Scott", "Chamberlain", role = c("aut", "cre"), email = "myrmecocystus@gmail.com", comment = c(ORCID="0000-0003-1444-9135")), person(given = "rOpenSci", role = "fnd", comment = "https://ropensci.org/"))
# License: MIT + file LICENSE
# URL: https://github.com/ropensci/solrium (devel), https://docs.ropensci.org/solrium/ (user manual)
# BugReports: https://github.com/ropensci/solrium/issues
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# Imports: utils, dplyr (>= 0.5.0), plyr (>= 1.8.4), crul (>= 0.4.0), xml2 (>= 1.0.0), jsonlite (>= 1.0), tibble (>= 1.4.2), R6
# Suggests: roxygen2 (>= 6.1.1), testthat, knitr
# RoxygenNote: 6.1.1
# X-schema.org-applicationCategory: Databases
# X-schema.org-keywords: database, search, JSON, XML, API, web
# X-schema.org-isPartOf: https://ropensci.org
# NeedsCompilation: no
# Packaged: 2019-10-21 17:44:04 UTC; sckott
# Author: Scott Chamberlain [aut, cre] (<https://orcid.org/0000-0003-1444-9135>), rOpenSci [fnd] (https://ropensci.org/)
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-10-21 18:10:02 UTC
