{% set version = "1.0.2" %}

package:
  name: r-solrium
  version: {{ version }}

source:
  fn: solrium_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/solrium_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/solrium/solrium_{{ version }}.tar.gz
  sha256: 0daecc6ea4a8689bd032dd447171e7dda146dc3df903cb0617424cee84f53e04

build:
  noarch: generic
  number: 1001
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-r6
    - r-crul >=0.4.0
    - r-dplyr >=0.5.0
    - r-jsonlite >=1.0
    - r-plyr >=1.8.4
    - r-tibble >=1.2
    - r-xml2 >=1.0.0
  run:
    - r-base
    - r-r6
    - r-crul >=0.4.0
    - r-dplyr >=0.5.0
    - r-jsonlite >=1.0
    - r-plyr >=1.8.4
    - r-tibble >=1.2
    - r-xml2 >=1.0.0

test:
  commands:
    - $R -e "library('solrium')"  # [not win]
    - "\"%R%\" -e \"library('solrium')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/solrium
  license: MIT
  license_file: LICENSE
  summary: Provides a set of functions for querying and parsing data from 'Solr'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
