appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: fENAupQ2Y9A7UwvMSh6AUTSyRlq8DB4oGHfD1OHAJEHhyr4u3qMF1zUsTWcT/T3aTgJMFxhtLmhHNH6ho1Hmr7Ez1LMoUubPaFz9H5lhOh4FQjUBrF8410O4D0Z2ZnxJ4Gx+mfjH7/oXX9kYTN4kn6OHBj/wBqcNeuYUxMAiLjYaFHMEySZHNHshpdeOXQVQa/jn/WOwFjYbzQYx/6AVpc64gv8/lfEE7iZeWJ3tlsrqVukf8VjwW8ilQvacjzPzWXWXJzpsEq1Zv5wb7LGAnaj0xfUIqAVbSvJ9F8+SjkgAL7XMIH8ftIBCqE0s+TLeSof/sXDYkHyhhyhis0UYZmuyxnfX/9geDduIauaEMH9/aKC9avKB+lsEB24IrUFvTkloVugmD0QCZl3ZDz4KVi1QeEjsv+lWW13gJeJzvVJhAaAmEN6BwCnScGrcC/VRgguLcE5dsT7D5mNdg/SfLLCV7xPDh6OWQQvHHpwxLY/cQaQlDijoc5n7FJ9+Ep3ewTQoElhtzvcxZj7V28i5Zpgu1FV6j79QiDPPs4CH20yEVXz4e7FZT9vLLC4D1NZnqJ/cDHny/ZBvJUakGnbKQ16TUIUoC9YG6QbTCklZG02Pw0xm11TIHlSadwdA9P3b4xfnievbvjK0Vi6D9N+ZVs7e1uadzhaKRVlt3A9zp8I=}
