travis:
  secure:
    BINSTAR_TOKEN: RhOMneNMBtF1G6twvyP4foBIEp1raLha5jjjXKJpd1z2dtM/77m4xxuORfJQuv/V5tH3VhJrAEGem1mOQ1YQnV1wBcq7bV6w6AwGlbtQBHfFWqOIioGa9xeJYIItO/R8IUToOIdGyl7VEGXRB0Bzegau4LgCHiae/xn1N29SCBUcLSGjF1j4U5eG2BH6lTgboRprJtbbH0yLzwgRRGdjjR+MsLCr/NQvOHhTOwAiF3IPbzKO8dY/wlsHG7mTmMOy8asFjrS/jnmSVBsPv0nY0UaPgRuXDk4QHrMWjPOBZ3UH2HiJ7xETPROSk6qH27DT1O3I9pZmPsgMs2pQ2apEKLp+RdpeJih9v6QhLhb5LRyw056FwsfSK4mu0kaJpDt96EyHbFOwpeo/xoeM3hAmHH6tWeo3/0GiP7Rx7pvyWkbruWifK7z1X7gJ3ZtrsbpTkACBc/W23gqQ4AdSsyIuMexFB8HVUuVFRh7G/WqI1N2fPeKrq/4znbagACUzeGTQklr9hr3MlXfyuM+Lf1LD1h8hPeiBN2K/iGtz3y55laQKE+ooTgeAM8NbxyJvlMXLlL+1krtJodPYnIZ7LSA9qt2CqL/Ab99FVsjUqFQ8P7PTw72knZpK/nXGrTTuyph9GBokp4klWO1vK8iT8UZcHqG4vdJgr5R4FOlao2dTEYQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
